### PR TITLE
trying to figure out folders

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by jordansread** [comment]
can you add your markdown to this repo?

**Comment by ldecicco-USGS** [comment]
huh?

I can't figure out why I lost my logo in the lower left corner.

**Comment by ldecicco-USGS** [comment]
OH...the markdown to make it. Yeah, sure

**Comment by ldecicco-USGS** [comment]
Are you developing yours here? Or in geoknife's repo?

**Pull request merged**
