### PR TITLE
Markdown

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
Still missing logo.....not sure when/why

**Comment by jordansread** [comment]
can you put the markdown in the markdown folder?

**Comment by ldecicco-USGS** [comment]
Didn't notice that. That's going to be a real test of my ability to define paths correctly. 2 dots are 1 folder above, right?

**Comment by ldecicco-USGS** [comment]
Nevermind, I see how you did it.

**Pull request merged**
